services:
  python-api:
    build: .
    ports:
      - 9000:9000
    environment:
      - env=dev
    networks:
      - devops

  # nginx:
  #   build: ./nginx
  #   # volumes:
  #     # static
  #     # - ./html5up-stellar/:/var/www/html
  #   ports:
  #     - 9000:80
  #     - 9443:443
  #   networks:
  #     - devops
  #   depends_on:
  #     - python-api
    
networks:
  devops:
    driver: bridge