pipeline {
    agent {
        docker {
            image 'python:slim-bullseye'
        }
    }
    
    stages {
        stage('Install Poetry for package management') {
            steps {
                echo 'Installing Poetry'
                sh 'pip install --no-cache-dir poetry'
                echo 'Poetry installed successfully'
            }
        
        }

        stage('Build') {
            steps {
                echo 'Using Poetry to install dependencies'
                // Build your FastAPI application
                // im using pyproject.toml
                // sh 'poetry install'
            }
        }
    }
}