pipeline {
    agent {
        docker {
            image 'python:slim-bullseye'
        }
    }
    
    stages {
        stage('Install Poetry for package management') {
            steps {
                echo 'Checking if /.local exists'
                sh '[ ! -d "/.local" ] && mkdir -p /.local'
                echo 'Changing ownership of /.local'
                sh 'chown 1000:1000 /.local'
                echo 'Installing Poetry'
                sh 'pip3 install --no-cache-dir --user poetry'
                echo 'Poetry installed successfully'
            }
        
        }

        stage('Build') {
            steps {
                echo 'Using Poetry to install dependencies'
                // Build your FastAPI application
                // im using pyproject.toml
                // sh 'poetry install'
            }
        }
    }
}