pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from version control...'
                // Checkout your code from version control
                // Replace the URL and credentials with your own
                git 'https://github.com/mavisphung/py-micros.git'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Build stage'
                echo 'Using Poetry to install dependencies'
                // Build your FastAPI application
                // im using pyproject.toml
                sh 'poetry install'
            }
        }
        
        // stage('Deploy') {
        //     steps {
        //         // Deploy your FastAPI application
        //         sh 'docker build -t my-fastapi-app .'
        //         sh 'docker run -d -p 8000:8000 my-fastapi-app'
        //     }
        // }
    }
}